version: '3.8'

services:
  backend:
    build: ./eupraxia-pleroma/backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://eupraxia:eupraxia@db:5432/eupraxia
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./eupraxia-pleroma/backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./eupraxia-pleroma/frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: eupraxia
      POSTGRES_PASSWORD: eupraxia
      POSTGRES_DB: eupraxia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: